const tableData = [
  {
    id: 1,
    user_id: 2,
    request_id: 11,
    transactionable_id: 3,
    transactionable_type: 'deposite',
    entity_id: 1,
    entity_name: 'entity',
    transaction_state_id: 1,
    currency: 'XAF',
    activity_title: 'ecommerce',
    money_flow: 'string',
    gross: 150,
    fee: 250,
    net: 15000,
    balance: 2000000,
    json_data: '',
    created_at: '31/11/2020',
    updated_at: '31/11/2020',
    currency_id: 2,
    currency_symbol: 'FCFA',
    thumb: 'string'
  },
  {
    id: 1,
    user_id: 2,
    request_id: 11,
    transactionable_id: 3,
    transactionable_type: 'deposite',
    entity_id: 1,
    entity_name: 'entity',
    transaction_state_id: 1,
    currency: 'XAF',
    activity_title: 'ecommerce',
    money_flow: 'string',
    gross: 150,
    fee: 250,
    net: 15000,
    balance: 2000000,
    json_data: '',
    created_at: '31/11/2020',
    updated_at: '31/11/2020',
    currency_id: 2,
    currency_symbol: 'FCFA',
    thumb: 'string'
  },
];

export { tableData };
